# Generated by Django 4.2.7 on 2023-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_set',
            field=models.JSONField(),
        ),
    ]
