# Generated by Django 4.2.7 on 2023-12-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_permission_permission_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='related_to',
            field=models.CharField(),
        ),
    ]
