# Generated by Django 4.2.7 on 2023-12-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_permission_related_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
