# Generated by Django 4.2.7 on 2023-12-01 21:26

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('product_related_perms', 'product_related_perms')], max_length=100, unique=True)),
                ('permission_set', models.JSONField(default=api.models.Permission.default_permission_dict)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_account', to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.permission'),
        ),
    ]
