# Generated by Django 4.2.7 on 2023-12-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_permission_alter_account_admin_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('product_related_perms', 'product_related_perms')], max_length=100),
        ),
    ]
