# Generated by Django 4.2.7 on 2023-11-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
