# Generated by Django 4.2.7 on 2023-12-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_permission_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='permission_type',
        ),
    ]
