# Generated by Django 4.2.7 on 2023-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(null=True, max_length=55),
            preserve_default=False,
        ),
    ]
