# Generated by Django 4.2.7 on 2023-12-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
    ]
